[package]
name = "counter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
zui-app = { path = "../../crates/zui-app" }
zui-core = { path = "../../crates/zui-core" }
zui-ui = { path = "../../crates/zui-ui" }

[dev-dependencies]
zui-platform = { path = "../../crates/zui-platform" }
zui-render = { path = "../../crates/zui-render" }
