[package]
name = "empty-window"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
zui-backend-winit = { path = "../../crates/zui-backend-winit" }
zui-core = { path = "../../crates/zui-core" }
zui-platform = { path = "../../crates/zui-platform" }
zui-render = { path = "../../crates/zui-render" }
zui-ui = { path = "../../crates/zui-ui" }
