[package]
name = "zui-backend-winit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
zui-core.workspace = true
zui-platform.workspace = true
winit.workspace = true

[dev-dependencies]
zui-render = { workspace = true, features = ["test-support"] }
